### ISSUE TITLE
Default Currency Issue

### ISSUE THREAD

**Issue by Joerocha** [vteams/open-source-billing#64]
Hi,

Hope someone can help, I am having trouble changing the default currency from USD to GBP ($ to £).
So I have set the "Default Currency" under "Settings -> Basic Settings" to "British Pound" however the dashboard still has all the values in $.
Maybe I am missing something?
Has anyone else ran into this?

Thanks in advanced.

**Comment by welshcoder** [comment]
Hi,

I have encountered this too. I've spent some time looking into this, and it's due to the default dollar symbol being selected in the code. It does this in a lot of places. The way I dealt with it is to change the default symbol to "£" instead of "$" in the code and leave it at that. If you want to change it, back up your config files and run `grep -rl \'\$\' *` and `grep -rl \"\$\" *` in the `<installation_directory>/app` directory. You will find most of the files that contains the code. Use your favourite text editor to change the dollar to pound (or whaterver you want) in those files. Do a search for "currency" and you will find the relevant code.

The second problem I found is that I wanted the "£" to be shown on the invoices/estimates/etc., and not "GBP". Again, use grep like this: `grep -rl currency.unit *` to find "currency.unit" in the files, and use your favourite text editor again to change `.unit` to `.code`. As far as I can see, there is no option to switch between the different style of presenting currency, so I've done it this way.

There could be more options for currency handling in this software, and it wouldn't be too difficult to add. But after playing around with it, I've decided to investigate other software as this one doesn't quite meet my needs. Good luck!

Cheers,
welshcoder
